#!/usr/bin/env bash

parse() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
    -h | --help) FLAG_HELP=1; break ;;
    conf) SUBCOM=conf; shift; ARGS="$@"; break ;;
    *) ARGS="$@"; break ;;
    esac
  done
}
parse "$@"
set -- $ARGS

show-help() {
  echo 'usage: command [conf|xxx]'
}

if [ "$FLAG_HELP" == "1" ]; then
  show-help
  exit
fi

### main proc
BASE="${HOME}/.cont"
NAME="${PWD//\//_}"
NAME="${NAME/_/}"
NAME="${NAME,,}"
CONF="${BASE}/${NAME}.mk"

if [ "$SUBCOM" == "conf" ]; then
  parse() {
    while [ "$#" -gt 0 ]; do
      case "$1" in
      -h | --help) FLAG_HELP=1; shift ;;
      -i | --image) IMG="$2"; shift 2 ;;
      -v | --vm) VM="$2"; shift 2 ;;
      -l | --list) FLAG_LIST=1; shift ;;
      -d | --delete) FLAG_DELETE=1; shift ;;
      -e | --edit) FLAG_EDIT=1; shift ;;
      -o | --overwrite) FLAG_OW=1; shift ;;
      *) ARGS="$@"; break ;;
      esac
    done
  }
  parse "$@"
  set -- $ARGS

  show-help() {
    echo 'usage: command conf [opt]
    -i|--image image
    -v|--vm vm (default:podman ex:docker)
    -l|--list
    -d|--delete
    -e|--edit
    -o|--overwrite
ex)
    cont conf -o -i node:latest --vm podman'
  }

  if [ "$FLAG_HELP" == "1" ]; then
    show-help
    exit
  fi

  if [ "$FLAG_LIST" == "1" ]; then
    ls "${BASE}"
    exit
  fi

  if [ "$FLAG_EDIT" == "1" ]; then
    EDIT="${VISUAL:-${EDITOR:-vi}}"
    exec "${EDIT}" "${CONF}"
  fi

  if [ "$FLAG_DELETE" == "1" ]; then
    rm -rf "${CONF}"
    exit
  fi

  ### main proc
  mkdir -p "${BASE}"

  if [ -e "${CONF}" ] && [ "$FLAG_OW" != "1" ]; then
    echo "Error: Configuration file already exists: ${CONF}"
    echo "Use -o or --overwrite option to overwrite it."
    exit 1
  fi

  # NOTE: Mac環境でdoc内文字多いと止まるがprintf使いたくないので分ける
  cat <<EOF > "${CONF}"
VM := ${VM:-podman}
NAME := ${NAME}
IMG := ${IMG:-$NAME}

all:
	@cat "$CONF"

build:
	\$(VM) build . -t \$(NAME)

rebuild:
	-cont stop
	-cont rm
	-cont rmi
	cont build

run:
	\$(VM) run --rm -v ./:/app -v /etc/localtime:/etc/localtime:ro -w /app -it --name \$(NAME) \$(IMG)

EOF

  cat <<EOF >> "${CONF}"
ever:
	@if \$(VM) ps -a --filter name=\$(NAME) --format "{{.Names}}" | grep -q \$(NAME); then \\
		\$(VM) start \$(NAME); \\
	else \\
		\$(VM) run -v ./:/app -v /etc/localtime:/etc/localtime:ro -w /app -itd --name \$(NAME) --entrypoint bash \$(IMG); \\
	fi

never:
	\$(VM) run --rm -v ./:/app -v /etc/localtime:/etc/localtime:ro -w /app -itd --name \$(NAME) --entrypoint bash \$(IMG)

EOF
  cat <<EOF >> "${CONF}"
stop:
	\$(VM) stop \$(NAME)

rm:
	\$(VM) rm \$(NAME)

rmi:
	\$(VM) rmi \$(NAME)

bash:
	\$(VM) exec -it \$(NAME) bash

EOF

  cat <<EOF >> "${CONF}"
#sync-time:
#	podman machine ssh date -u -s "\$\$(date -u +'%Y-%m-%dT%H:%M:%S')"

#proxy:
#	\$(VM) exec -it \$(NAME) socat -v 'tcp4-listen:8443,fork,reuseaddr' 'tcp4:127.0.0.1:443'
EOF

exit 0
fi

if [ ! -e "${CONF}" ]; then
  show-help
  exit
fi

make -f "${CONF}" "$@"
