#!/bin/sh

CMD_NAME=$(basename "$0")

parse() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
    -h | --help) FLAG_HELP=1; break ;;
    *) ARGS="$@"; break ;;
    esac
  done
}
parse "$@"
set -- $ARGS

if [ "${FLAG_HELP}" = "1" ]; then
  echo "Usage: ${CMD_NAME} [opts]" >&2
  exit 1
fi

### main proc
WORK_DIR=$(dirname "$0")
eval "$("${WORK_DIR}/cont-conf" env)"

if [ ! -e "${CONF}" ]; then
  echo "Error: Configuration file does not exist: ${CONF}" >&2
  echo "Create it with: ${CMD_NAME}-conf new" >&2
  exit 1
fi

make -f "${CONF}" "$@"
