all:
	@echo 'podman run -itd id'
	@echo 'podman build . -it name'
	@echo 'podman stop $$(podman ps -q)'
	@echo 'podman stop -l'
	@echo 'podman rm $$(podman ps -q -a)'
	@echo 'podman rm -l'
	@echo 'podman run --name php -d -it localhost/proxy-cache'
	@echo 'https://github.com/containers/podman/blob/main/troubleshooting.md'
